// src/component/NoteContext.svelte
<script lang="ts">
	import { liveQuery, type Observable } from "dexie"
	import { TFile } from "obsidian"
	import type { LlmDexie, NoteDerivedData } from "src/storage/db"
	import { readable, writable } from "svelte/store"
	import { appStore, settingsStore } from "src/utils/obsidian"
	import { extractKeyTopics, noteSummary } from "src/utils/openai"
	import type { KeyTopic } from "./types"
	import ObsidianIcon from "./obsidian/ObsidianIcon.svelte"
	import TailwindCss from "./TailwindCSS.svelte"

	export let db: LlmDexie

	// TODO: add UI that displays when this happens
	const minChars = 500

	let element: HTMLElement | undefined

	const openFile = readable($appStore.workspace.getActiveFile(), (set) => {
		const onOpen = (f: TFile | null) => {
			set(f)
		}
		$appStore.workspace.on("file-open", onOpen)
		return () => $appStore.workspace.off("file-open", onOpen)
	})

	let derivedData: Observable<NoteDerivedData | undefined>
	$: derivedData = liveQuery(async () => {
		if (!$openFile) return

		return await db.getNoteDerivedData($openFile.path)
	})

	let keyTopics: KeyTopic[]
	$: keyTopics =
		$derivedData?.keyTopics?.map((t) => {
			return {
				name: t,
				file: $appStore.metadataCache.getFirstLinkpathDest(t, ""),
			}
		}) ?? []

	let networkLoading = writable(false)
	const fetchSummary = async (f: TFile) => {
		const text = await $appStore.vault.cachedRead(f)
		if (text.length < minChars) return

		try {
			networkLoading.set(true)
			const summary = await noteSummary(text, $settingsStore?.anthropicApikey)
			await db.updateNoteSummary(f.path, summary)
		} catch (e) {
			console.error(e)
		} finally {
			networkLoading.set(false)
		}
	}
	const fetchTopics = async (f: TFile) => {
		const text = await $appStore.vault.cachedRead(f)
		if (text.length < minChars) return

		try {
			networkLoading.set(true)
			const topics = await extractKeyTopics(text, $settingsStore?.openAIApiKey)
			await db.updateNoteKeyTopics(f.path, topics)
		} catch (e) {
			console.error(e)
		} finally {
			networkLoading.set(false)
		}
	}

	openFile.subscribe(async (f) => {
		if (!f || $settingsStore.openAIApiKey === "") return

		if (!element || !element.isShown()) return

		const localData = await db.getNoteDerivedData(f.path)
		if (!localData) {
			fetchSummary(f)
			fetchTopics(f)
		}
	})

	const onRecompute = async () => {
		if (!$openFile) return
		await db.deleteNoteDerivedData($openFile.path)
		fetchTopics($openFile)
		fetchSummary($openFile)
	}
	const onKeyTopicClick = (path: string) => {
		$appStore.workspace.openLinkText(path, "", "tab")
	}
</script>

<TailwindCss />
<h6 bind:this={element}>{$openFile?.basename ?? ""}</h6>
<button on:click={onRecompute} class="icon-button" aria-label="Recompute" data-tooltip-delay="300">
	<ObsidianIcon iconId="refresh-cw" size="s" />
</button>

{#if $networkLoading}
	<div>Loading...</div>
{/if}

{#if $derivedData?.summary}
	<h6>Summary</h6>
	<p>{$derivedData.summary}</p>
{/if}

{#if keyTopics && keyTopics.length > 0}
	<h6>Key topics</h6>
	<ul>
		{#each keyTopics as topic}
			<li>
				{#if topic.file}
					<!-- svelte-ignore a11y-invalid-attribute -->
					<a href="#" on:click={() => onKeyTopicClick(topic.file?.path ?? "")}
						>{topic.name}</a
					>
				{:else}
					<div class="flex flex-row items-center group">
						<span class="mr-1">{topic.name}</span>
						<span
							class="clickable-icon invisible group-hover:visible"
							aria-label="Create note"
						>
							<ObsidianIcon iconId="file-plus" size="xs" />
						</span>
					</div>
				{/if}
			</li>
		{/each}
	</ul>
{/if}

// component/NoteContext.tsx
import { useLiveQuery } from "dexie-react-hooks";
import { App, TFile } from "obsidian";
import { useContext, useEffect, useState, useMemo, useCallback } from "preact/hooks"
import { LlmDexie } from "storage/db";
import { extractKeyTopics, noteSummary } from "utils/openai";
import { AppContext, PluginSettingsContext } from "utils/obsidian";

const summaryMinChars = 500;

export const NoteContext = (props: { db: LlmDexie }) => {
	const app = useContext(AppContext);
	const settings = useContext(PluginSettingsContext);
	const [file, setFile] = useState(app?.workspace.getActiveFile() ?? null);

	const [isLoading, setLoading] = useState(false);

	useEffect(() => {
		const onOpen = (file: TFile | null) => {
			setFile(file)
		};
		app?.workspace.on("file-open", onOpen)
		return () => app?.workspace.off("file-open", onOpen);
	}, [app]);

	const derivedData = useLiveQuery(async () => {
		if (!file) {
			return;
		}
		return await props.db.getNoteDerivedData(file?.path)
	}, [file?.path]);

	const fetchSummary = useCallback(async () => {
		if (!file || !app || !settings?.openAIApiKey) {
			return;
		}

		const dataInDB = await props.db.getNoteDerivedData(file.path);
		if (dataInDB?.summary) {
			return;
		}

		const text = await app.vault.cachedRead(file);
		if (text.length < summaryMinChars) {
			return;
		}

		try {
			setLoading(true);

			const summary = await noteSummary(text, settings?.openAIApiKey);
			props.db.updateNoteSummary(file.path, summary);
			setLoading(false);
			return;
		} catch (e) {
			setLoading(false);
			console.error(e);
			return;
		}
	}, [file?.path]);
	useEffect(() => {
		fetchSummary();
	}, [fetchSummary]);

	const fetchTopics = useCallback(async () => {
		if (!file || !app || !settings?.openAIApiKey) {
			return;
		}

		// TODO: force refresh won't work this way
		const dataInDB = await props.db.getNoteDerivedData(file.path);
		if (dataInDB?.keyTopics && dataInDB.keyTopics.length > 0) {
			return;
		}

		try {
			setLoading(true);
			const text = await app.vault.cachedRead(file);
			const topics = await extractKeyTopics(text, settings.openAIApiKey);
			props.db.updateNoteKeyTopics(file.path, topics);
			setLoading(false);
			return;
		} catch (e) {
			setLoading(false);
			console.error(e);
			return;
		}
	}, [file?.path]);
	useEffect(() => {
		fetchTopics();
	}, [fetchTopics]);


	const onRecompute = () => {
		if (!file) return;

		props.db.deleteNoteDerivedData(file.path);
		fetchSummary();
		fetchTopics();
	};

	return <div>
		<h4>{file?.basename}</h4>
		{file && <button onClick={onRecompute}>Recompute</button>}

		{isLoading && <div>Loading...</div>}

		{derivedData?.summary && <>
			<h6>Summary</h6>
			<p>{derivedData.summary}</p>
		</>}

		{derivedData?.keyTopics && derivedData.keyTopics.length > 0 && <>
			<h6>Key topics</h6>
			<ul>
				{/* TODO: unique key */}
				{derivedData.keyTopics.map(topic => <li key={topic}>{topic}</li>)}
			</ul>
		</>}
	</div>;
};
