// component/QuestionAndAnswer.svelte
<script lang="ts">
	import type { DebugInfo, QueryResponse } from "rag/synthesizer"
	import { createEventDispatcher, type ComponentEvents } from "svelte"
	import SourceList from "./SourceList.svelte"
	import SvelteMarkdown from "svelte-markdown"

	export let isLoading = false
	export let queryResponse: QueryResponse | null

	const dispatch = createEventDispatcher<{
		"query-submit": string
		"source-click": string
	}>()

	let query = ""

	const onSubmit = (event: SubmitEvent) => {
		event.preventDefault()
		dispatch("query-submit", query)
	}
</script>

<form on:submit={onSubmit}>
	<textarea
		disabled={isLoading}
		placeholder="Ask a question"
		bind:value={query}
	/>
	<button disabled={isLoading} type="submit">
		Ask
		{#if isLoading}...{/if}
	</button>
</form>
{#if queryResponse}
	<div>
		<div class="completion">
			<SvelteMarkdown source={queryResponse.text} />
		</div>
		<SourceList queryResponse={queryResponse} on:source-click />
	</div>
{/if}



<style>
	textarea {
		width: 100%;
	}
</style>

// component/QuestionAndAnswer.tsx
import { TFile } from "obsidian"
import { useState } from "preact/hooks"
import { QueryResponse } from "rag/synthesizer"

interface QuestionAndAnswerProps {
	file: TFile
	isLoading: boolean
	queryResponse?: QueryResponse
	onQuestionSubmit: (q: string) => void
}


export const QuestionAndAnswer = (props: QuestionAndAnswerProps) => {
	const [question, setQuestion] = useState("")
	const onSubmit = (e: SubmitEvent) => {
		if (question) {
			props.onQuestionSubmit(question)
		}
		e.preventDefault()
	}
	const onInput = (e: InputEvent) => {
		setQuestion((e.target as HTMLInputElement).value)
	}

	return (
		<div>
			<form onSubmit={onSubmit}>
				<input
					type="text"
					disabled={props.isLoading}
					placeholder="Ask a question"
					value={question}
					onInput={onInput}
				/>
				<button type="submit" disabled={props.isLoading}>
					Send
					{props.isLoading && "..."}
				</button>
			</form>
			{props.queryResponse && (
				<div>
					<div class="llm-workspace-completion">{props.queryResponse.text}</div>
					<ol>
						{props.queryResponse.sources.map((node) => (
							<li>{node.parent}</li>
						))}
					</ol>
				</div>
			)}
		</div>
	)
}
